version: '3.9'
services:
  backend:
    build:
      context: ./demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./demo:/app
      - /app/target
  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./my-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
